export const BASIC_LANDS_PT = new Map([
  ["planicie", "Plains"],
  ["pantano", "Swamp"],
  ["montanha", "Mountain"],
  ["ilha", "Island"],
  ["floresta", "Forest"]
]);

export const PT_CARD_ALIASES = new Map([
  ["kaalia, buscadora do zenite", "Kaalia, Zenith Seeker"],
  ["arcanjo resoluto", "Resolute Archangel"],
  ["akroma, anjo da ira", "Akroma, Angel of Wrath"],
  ["akroma, anjo da furia", "Akroma, Angel of Fury"],
  ["terror dos picos", "Terror of the Peaks"],
  ["pairoo, a volatil", "Piru, the Volatile"],
  ["anjo da serenidade", "Angel of Serenity"],
  ["vilis, negociante de sangue", "Vilis, Broker of Blood"],
  ["reya, portadora da alvorada", "Reya Dawnbringer"],
  ["sephara, lamina dos ceus", "Sephara, Sky's Blade"],
  ["gisela, espadachim dos noite dourada", "Gisela, Blade of Goldnight"],
  ["flagelo do trono", "Scourge of the Throne"],
  ["arcanjo avacyn", "Archangel Avacyn"],
  ["bruna, a luz desvanecente", "Bruna, the Fading Light"],
  ["arbitro angelical", "Angelic Arbiter"],
  ["aurelia, lider de guerra", "Aurelia, the Warleader"],
  ["anjo do desespero", "Angel of Despair"],
  ["drakuseth, gorja das chamas", "Drakuseth, Maw of Flames"],
  ["rakdos, patrono do caos", "Rakdos, Patron of Chaos"],
  ["demonio das cicatrizes runicas", "Rune-Scarred Demon"],
  ["demonio da oferenda de sangue", "Bloodgift Demon"],
  ["ceifador de almas", "Harvester of Souls"],
  ["anjo das ruinas", "Angel of the Ruins"],
  ["anjo da egide", "Aegis Angel"],
  ["terror do monte velo", "Terror of Mount Velus"],
  ["shilgengar, gerador da fome", "Shilgengar, Sire of Famine"],
  ["liesa, arcanjo esquecido", "Liesa, Forgotten Archangel"],
  ["anel solar", "Sol Ring"],
  ["sinete arcano", "Arcane Signet"],
  ["bijuteria do viajante", "Wayfarer's Bauble"],
  ["bussola taumatica", "Thaumatic Compass"],
  ["sinete rakdos", "Rakdos Signet"],
  ["sinete orzhov", "Orzhov Signet"],
  ["sinete boros", "Boros Signet"],
  ["talisma da conviccao", "Talisman of Conviction"],
  ["talisma da hierarquia", "Talisman of Hierarchy"],
  ["talisma da indulgencia", "Talisman of Indulgence"],
  ["grevas faiscantes", "Lightning Greaves"],
  ["botas pe-ligeiro", "Swiftfoot Boots"],
  ["manto de seda ruflante", "Whispersilk Cloak"],
  ["arena phyrexiana", "Phyrexian Arena"],
  ["prisao fantasmagorica", "Ghostly Prison"],
  ["agouro dos devedores", "Debtors' Knell"],
  ["retorica sagaz", "Cunning Rhetoric"],
  ["caminho para o exilio", "Path to Exile"],
  ["espadas em arados", "Swords to Plowshares"],
  ["descentelhar", "Despark"],
  ["fraturar", "Fracture"],
  ["presente generoso", "Generous Gift"],
  ["batida da meia-noite", "Stroke of Midnight"],
  ["promessa de lealdade", "Promise of Loyalty"],
  ["ultimato ruinoso", "Ruinous Ultimatum"],
  ["comando austero", "Austere Command"],
  ["sussurro da noite", "Night's Whisper"],
  ["leia os ossos", "Read the Bones"],
  ["verdades dolorosas", "Painful Truths"],
  ["assinar com sangue", "Sign in Blood"],
  ["exigir respostas", "Demand Answers"],
  ["frisson das possibilidades", "Thrill of Possibility"],
  ["seu templo esta sendo atacado", "Your Temple Is Under Attack"],
  ["custo da ambicao", "Ambition's Cost"],
  ["amuleto boros", "Boros Charm"],
  ["torre de comando", "Command Tower"],
  ["pomar exotico", "Exotic Orchard"],
  ["posto avancado nomade", "Nomad Outpost"],
  ["caminho da ascendencia", "Path of Ancestry"],
  ["templo da maleficencia", "Temple of Malice"],
  ["templo do triunfo", "Temple of Triumph"],
  ["templo do silencio", "Temple of Silence"],
  ["charco ensolarado", "Sunlit Marsh"],
  ["charco geotermico", "Geothermal Bog"],
  ["picos sagrados", "Sacred Peaks"],
  ["cavernas sanguinarias", "Bloodfell Caves"],
  ["penhasco marcado pelo vento", "Wind-Scarred Crag"],
  ["pico da caveira de dragao", "Dragonskull Summit"],
  ["capela isolada", "Isolated Chapel"],
  ["retiro da falesia", "Clifftop Retreat"],
  ["liame da calmafuriosa", "Furycalm Snarl"],
  ["liame do umbrolume", "Shineshadow Snarl"],
  ["ruinas agourentas", "Foreboding Ruins"],
  ["forjaria do campo de batalha", "Battlefield Forge"],
  ["cavernas de koilos", "Caves of Koilos"],
  ["pantano ardente", "Sulfurous Springs"],
  ["desolacao de cinzas", "Cinder Barrens"],
  ["santuario abandonado", "Forsaken Sanctuary"],
  ["paisagem infinita", "Myriad Landscape"],
  ["torre do relicario", "Reliquary Tower"]
]);
