import { normalizeCardName } from "./normalize-card-name.ts";

export const LOCAL_ALIASES: Record<string, string> = {
  "pantano": "Swamp",
  "pântano": "Swamp",
  "ritual sombrio": "Dark Ritual",
  "tutor diabolico": "Diabolic Tutor",
  "tutor diabólico": "Diabolic Tutor",
  "pedra da mente": "Mind Stone",
  "diamante de carvao": "Charcoal Diamond",
  "diamante de carvão": "Charcoal Diamond",
  "gavinhas da agonia": "Tendrils of Agony",
  "mercador cinzento de asfodelos": "Gray Merchant of Asphodel",
  "cidadela de nicol bolas": "Bolas's Citadel",
  "maquinacoes de gonti": "Gonti's Machinations",
  "maquinações de gonti": "Gonti's Machinations",
  "alimentar o enxame": "Feed the Swarm",
  "malignidade imortal": "Undying Malice",
  "armadura de sombras": "Armor of Shadows",
  "presenca medonha": "Dread Presence",
  "presença medonha": "Dread Presence",
  "lente prismatica": "Prismatic Lens",
  "lente prismática": "Prismatic Lens",
  "pluma do paraiso": "Paradise Plume",
  "pluma do paraíso": "Paradise Plume",
  "chifre de demonio": "Demon's Horn",
  "chifre de demônio": "Demon's Horn",
  "promessa de poder": "Promise of Power",
  "chainer mestre da demencia": "Chainer, Dementia Master",
  "chainer mestre da demência": "Chainer, Dementia Master",
  "pestilencia": "Pestilence",
  "pestilência": "Pestilence",
  "elixir da imortalidade": "Elixir of Immortality",
  "passagem do ladino": "Rogue's Passage",
  "parasita thrull": "Thrull Parasite",
  "sibilador da basilica": "Basilica Screecher",
  "sibilador da basílica": "Basilica Screecher",
  "impositor do sindicato": "Syndicate Enforcer",
  "pontifice do flagelo": "Pontiff of Blight",
  "pontífice do flagelo": "Pontiff of Blight",
  "cajado do magus da morte": "Staff of the Death Magus",
  "fonte radiante": "Radiant Fountain",
  "anel de prisma": "Prism Ring",
  "fonte das agonias": "Font of Agonies",
  "macular": "Defile",
  "rito de razaketh": "Razaketh's Rite",
  "torre de comando": "Command Tower",
  "manto de seda ruflante": "Whispersilk Cloak",
  "leia os ossos": "Read the Bones",
  "paisagem infinita": "Myriad Landscape",
  "dragao decadente": "Decadent Dragon",
  "dragão decadente": "Decadent Dragon",
  "gosto refinado": "Expensive Taste",
  "impeto brilhante": "Shiny Impetus",
  "ímpeto brilhante": "Shiny Impetus",
  "onda desmanteladora": "Dismantling Wave",
  "redemoinho de pensamentos": "Whirlwind of Thought",
  "mangara, o diplomata": "Mangara, the Diplomat",
  "epifania sublime": "Sublime Epiphany",
  "comando de prismari": "Prismari Command",
  "arquimago emerito": "Archmage Emeritus",
  "arquimago emérito": "Archmage Emeritus",
  "artista da fornalha tempestuosa": "Storm-Kiln Artist",
  "velomaco sapioforte": "Velomachus Lorehold",
  "iteracao expressiva": "Expressive Iteration",
  "iteração expressiva": "Expressive Iteration",
  "veyran, voz da dualidade": "Veyran, Voice of Duality",
  "considerar": "Consider",
  "lier, discipulo dos afogados": "Lier, Disciple of the Drowned",
  "lier, discípulo dos afogados": "Lier, Disciple of the Drowned",
  "subjugar a horda": "Vanquish the Horde",
  "dragao averneo manaforme": "Manaform Hellkite",
  "dragão averneo manaforme": "Manaform Hellkite",
  "sorte grande": "Big Score",
  "genio arrogante": "Haughty Djinn",
  "gênio arrogante": "Haughty Djinn",
  "iconoclasta da terceira via": "Third Path Iconoclast",
  "baral e kari zev": "Baral and Kari Zev",
  "planicie": "Plains",
  "ilha": "Island",
  "montanha": "Mountain",
  "floresta": "Forest",
  "mascara de avacyn": "Mask of Avacyn",
  "fera interior": "Beast Within",
  "batedor chifre-de-cobre": "Copperhorn Scout",
  "elfo do arvoredo": "Arbor Elf",
  "druida devotado": "Devoted Druid",
  "elfo porto-longinquo": "Farhaven Elf",
  "proeza do belo": "Prowess of the Fair",
  "passo elfico": "Elvish Promenade",
  "magistrado imaculado": "Immaculate Magistrate",
  "perfeita imperiosa": "Imperious Perfect",
  "dourador de folhas": "Leaf Gilder",
  "mestre de caca de lys alana": "Lys Alana Huntmaster",
  "retorno aterrorizante": "Dread Return",
  "garra krosana": "Krosan Grip",
  "elfos de fyndhorn": "Fyndhorn Elves",
  "elfos das sombras profundas": "Elves of Deep Shadow",
  "pastoras magi-anuladoras": "Nullmage Shepherd",
  "putrificar": "Putrefy",
  "chifres de vorrac para combate": "Vorrac Battlehorns",
  "elfo vigia dos pinheiros": "Timberwatch Elf",
  "drenar mente": "Mind Drain",
  "patrulheiros betulineos": "Birchlore Rangers",
  "voz das matas": "Voice of the Woods",
  "mortos de llanowar": "Llanowar Dead",
  "inconsciente coletivo": "Collective Unconscious",
  "sacerdote de titania": "Priest of Titania",
  "elfos da floresta": "Wood Elves",
  "patrulheiro de skyshroud": "Skyshroud Ranger",
  "vitalizar": "Vitalize",
  "arqueodruida elfo": "Elvish Archdruid",
  "elfos de llanowar": "Llanowar Elves",
  "homicidio": "Murder",
  "amuleto golgari": "Golgari Charm",
  "autoridade de alfa": "Alpha Authority",
  "mistico elfico": "Elvish Mystic",
  "elmo do espreitador": "Prowler's Helm",
  "templo da enfermidade": "Temple of Malady",
  "sabio da reivindicacao": "Reclamation Sage",
  "no rastro de garruk": "In Garruk's Wake",
  "clareira na selva": "Jungle Hollow",
  "revelacao xamanica": "Shamanic Revelation",
  "pacto condenavel": "Damnable Pact",
  "dwynen, daen de folha d'ouro": "Dwynen, Gilt-Leaf Daen",
  "xama do bando": "Shaman of the Pack",
  "druida do capote": "Druid of the Cowl",
  "bestiario do vivideiro": "Lifecrafter's Bestiary",
  "marwyn, a nutriz": "Marwyn, the Nurturer",
  "arqueiro da ponta envenenada": "Poison-Tip Archer",
  "encantador de feras": "Beast Whisperer",
  "druida do paraiso": "Paradise Druid",
  "baixas de guerra": "Casualties of War",
  "tribo de llanowar": "Llanowar Tribe",
  "recuperacao das gavinhas bolorentas": "Moldervine Reclamation",
  "mistica da mata": "Woodland Mystic",
  "escudo espelhado": "Mirror Shield",
  "ritos da vila": "Village Rites",
  "abominacao de llanowar": "Abomination of Llanowar",
  "abismo da floresta": "Woodland Chasm",
  "umbrosabia de skemfar": "Skemfar Shadowsage",
  "harald, rei de skemfar": "Harald, King of Skemfar",
  "vingadora de skemfar": "Skemfar Avenger",
  "coroa de skemfar": "Crown of Skemfar",
  "peconha da presa ancestral": "Elderfang Venom",
  "pacto da serpente": "Pact of the Serpent",
  "ponte de musgosombrio": "Darkmoss Bridge",
  "paisagem perigosa": "Perilous Landscape",
  "a pedra fellwar": "Fellwar Stone",
  "aberrante": "Aberrant",
  "abocanhar": "Bite Down",
  "abrasao": "Abrade",
  "abrigo de sejiri": "Sejiri Shelter",
  "acolito de carametra": "Karametra's Acolyte",
  "adaptavel em evolucao": "Evolving Adaptive",
  "adeline, catara resplandecente": "Adeline, Resplendent Cathar",
  "adversario de carvalhandia": "Oakhame Adversary",
  "adversario primal": "Primal Adversary",
  "ajuste de contas divino": "Divine Reckoning",
  "alela, conquistadora ardilosa": "Alela, Cunning Conqueror",
  "amargo triunfo": "Bitter Triumph",
  "amuleto boros": "Boros Charm",
  "anel solar": "Sol Ring",
  "anjo da egide": "Aegis Angel",
  "anjo da explosao solar": "Sunblast Angel",
  "anjo da finalidade": "Angel of Finality",
  "anjo da invencao": "Angel of Invention",
  "anjo da vitalidade": "Angel of Vitality",
  "anjo do requiem": "Requiem Angel",
  "anjo estilhacado": "Shattered Angel",
  "anjo exterminador do mal": "Baneslayer Angel",
  "anjo subjugador": "Subjugator Angel",
  "anunciador de garruk": "Garruk's Harbinger",
  "anunciadora feerica": "Faerie Harbinger",
  "aprendiz leal": "Loyal Apprentice",
  "aqueduto dimir": "Dimir Aqueduct",
  "arauta da guerra": "Herald of War",
  "arauto multiplicador": "Herald of the Host",
  "arcanjo indomavel": "Indomitable Archangel",
  "armadura emaranhada": "Tangleweave Armor",
  "arquetipo da resistencia": "Archetype of Endurance",
  "arquimaga de glen elendra": "Glen Elendra Archmage",
  "arquimago dos ecos": "Archmage of Echoes",
  "artesaos feericos": "Faerie Artisans",
  "atlas infinito": "Endless Atlas",
  "aurora da esperanca": "Dawn of Hope",
  "ausencia inesperada": "Unexpectedly Absent",
  "avacyn, anjo da guarda": "Avacyn, Guardian Angel",
  "baloths enfurecidos": "Rampaging Baloths",
  "bandida das asas malditas": "Blightwing Bandit",
  "bastiao da recordacao": "Bastion of Remembrance",
  "batida da meia-noite": "Stroke of Midnight",
  "beliscadora furtiva": "Sneaky Snacker",
  "bijuteria do viajante": "Wayfarer's Bauble",
  "boas-vindas de tocasia": "Tocasia's Welcome",
  "botas pe-ligeiro": "Swiftfoot Boots",
  "brontodonte destruidor": "Thrashing Brontodon",
  "brontodonte enfurecido": "Rampaging Brontodon",
  "bruxa chiadora": "Chittering Witch",
  "busca frenetica": "Frantic Search",
  "calice do fluxo perene": "Everflowing Chalice",
  "caloteiro descarado": "Brazen Borrower",
  "camara do arcanjo": "Vault of the Archangel",
  "caminho da ascendencia": "Path of Ancestry",
  "caminho para o exilio": "Path to Exile",
  "campeao da lamina de aco": "Steel Leaf Champion",
  "capela isolada": "Isolated Chapel",
  "carcereiro do palacio": "Palace Jailer",
  "carneirada": "Ram Through",
  "castelo de brasoreth": "Castle Embereth",
  "castelo do vale arden": "Castle Ardenvale",
  "catacumbas de darkwater": "Darkwater Catacombs",
  "cavernas de koilos": "Caves of Koilos",
  "comandante do grupo de cerco": "Siege-Gang Commander",
  "comandante dos noite dourada": "Goldnight Commander",
  "comando austero": "Austere Command",
  "conclave feerico": "Faerie Conclave",
  "contradicao arcana": "Arcane Denial",
  "conventiculo do magiscarnio": "Spellscorn Coven",
  "crescimento virente": "Wild Growth",
  "cristal do orador das pedras": "Stonespeaker Crystal",
  "cumes dos ventos velozes": "Windbrisk Heights",
  "cutilada banidora": "Banishing Slash",
  "dadiva de boseiju": "Boon of Boseiju",
  "degolador de zulaport": "Zulaport Cutthroat",
  "descentelhar": "Despark",
  "desvio de realidade": "Reality Shift",
  "diabo do pandemonio": "Mayhem Devil",
  "diario do investigador": "Investigator's Journal",
  "disputa mortifera": "Deadly Dispute",
  "dissolucao pesadelar": "Nightmare Unmaking",
  "dominancia da estirpe": "Kindred Dominance",
  "elas il-kor, peregrina sadica": "Elas il-Kor, Sadistic Pilgrim",
  "enclave dos vinculadores": "Bonders' Enclave",
  "envolto em vigor": "Wrap in Vigor",
  "escaramucadora angelical": "Angelic Skirmisher",
  "escolha sua arma": "Choose Your Weapon",
  "escorracamento de tegwyll": "Tegwyll's Scouring",
  "esmagar o contrabando": "Crush Contraband",
  "espadas em arados": "Swords to Plowshares",
  "especialidade de rishkar": "Rishkar's Expertise",
  "espirito altruista": "Selfless Spirit",
  "estalo": "Snap",
  "estuario estrangulado": "Choked Estuary",
  "eterno-deus rhonas": "God-Eternal Rhonas",
  "faccao laco de brumas": "Mistbind Clique",
  "faccao titeriteira": "Puppeteer Clique",
  "faccao vendilion": "Vendilion Clique",
  "fanatico de rhonas": "Fanatic of Rhonas",
  "fim do semestre": "Semester's End",
  "florescencia amarga": "Bitterblossom",
  "floresta flagelada": "Blighted Woodland",
  "forjaria do campo de batalha": "Battlefield Forge",
  "formacao feerica": "Faerie Formation",
  "formacao inquebravel": "Unbreakable Formation",
  "forrageadora de halo": "Halo Forager",
  "fuga de loran": "Loran's Escape",
  "fulgor mesmerizante": "Mesmeric Glare",
  "gagueira magica": "Spell Stutter",
  "gargantilha liquometalica": "Liquimetal Torque",
  "garna, punho sangrento de keld": "Garna, Bloodfist of Keld",
  "garra cruenta, terror de qal sisma": "Goreclaw, Terror of Qal Sisma",
  "gerador de terrenos": "Terrain Generator",
  "ghalta, fome primordial": "Ghalta, Primal Hunger",
  "giada, fonte de esperanca": "Giada, Font of Hope",
  "gix, pretor de yawgmoth": "Gix, Yawgmoth Praetor",
  "gladiodonte descontrolado": "Wayward Swordtooth",
  "grande crescendo": "Grand Crescendo",
  "grevas faiscantes": "Lightning Greaves",
  "guia carmico": "Karmic Guide",
  "harmonizar": "Harmonize",
  "heroi de bladehold": "Hero of Bladehold",
  "heroi do povo": "Folk Hero",
  "hidra devoradora de mana": "Managorger Hydra",
  "hora de avaliacao": "Hour of Reckoning",
  "horda de garruk": "Garruk's Horde",
  "idolo do oblivio": "Idol of Oblivion",
  "ilha contaminada": "Tainted Isle",
  "impostora manipulavel": "Malleable Impostor",
  "incomodo irritante": "Nettling Nuisance",
  "insignia do comandante": "Commander's Insignia",
  "instigar a multidao": "Rabble Rousing",
  "jorra-fogo": "Fireshrieker",
  "kambal, prefeito especulador": "Kambal, Profiteering Mayor",
  "kaya, cacadora de geists": "Kaya, Geist Hunter",
  "laceradora da lamina mental": "Mindblade Render",
  "lamacal do desfiladeiro": "Canyon Slough",
  "lamina dos egos": "Blade of Selves",
  "lamineiro fada": "Faerie Bladecrafter",
  "lealdade da legiao": "Legion Loyalty",
  "levante de garruk": "Garruk's Uprising",
  "libertar as fadinas": "Free the Fae",
  "lider de matilha de garruk": "Garruk's Packleader",
  "lider de matilha de lobisomens": "Werewolf Pack Leader",
  "ligeirideo": "Quickling",
  "lodo necrofago": "Scavenging Ooze",
  "lulu, halofante leal": "Lulu, Loyal Hollyphant",
  "mahadi, mestre do emporio": "Mahadi, Emporium Master",
  "majestade colossal": "Colossal Majesty",
  "manto assombrado": "Haunted Cloak",
  "mascara da memoria": "Mask of Memory",
  "matagal fetido": "Fetid Heath",
  "matriz de simetria": "Symmetry Matrix",
  "melodia distante": "Distant Melody",
  "mensageiro de emrakul": "Emrakul's Messenger",
  "mensageiro de talion": "Talion's Messenger",
  "mente mestra feerica": "Faerie Mastermind",
  "missao de reconhecimento": "Reconnaissance Mission",
  "monumento de rhonas": "Rhonas's Monument",
  "morcegos da floresta das trevas": "Mirkwood Bats",
  "nuvem de fadas": "Cloud of Faeries",
  "nymris, trapaceiro de oona": "Nymris, Oona's Trickster",
  "obyra, duelista sonhadora": "Obyra, Dreaming Duelist",
  "ofiomante": "Ophiomancer",
  "ogro guia de batalha": "Ogre Battledriver",
  "oona, rainha das fadinas": "Oona, Queen of the Fae",
  "opor resistencia": "Make a Stand",
  "oportunista morbida": "Morbid Opportunist",
  "optar": "Opt",
  "orador incendiario": "Witty Roastmaster",
  "paisagem despedacada": "Shattered Landscape",
  "pantano ardente": "Smoldering Marsh",
  "pantano de bojuka": "Bojuka Bog",
  "pastora de emeria": "Emeria Shepherd",
  "pastora do cosmos": "Shepherd of the Cosmos",
  "pequeno furto": "Petty Theft",
  "percepcao do cacador": "Hunter's Insight",
  "pico da caveira de dragao": "Dragonskull Summit",
  "pinca craniana": "Skullclamp",
  "pisoteador de topiaria": "Topiary Stomper",
  "poco dos sonhos perdidos": "Well of Lost Dreams",
  "pomar exotico": "Exotic Orchard",
  "posto avancado nomade": "Nomad Outpost",
  "presente generoso": "Generous Gift",
  "prole de oona": "Scion of Oona",
  "proteger os ermos": "Secure the Wastes",
  "protetora do santuario": "Sanctuary Warden",
  "punicao de heliode": "Heliod's Punishment",
  "rankle, mestre das pecas": "Rankle, Master of Pranks",
  "raptor corpulento": "Hulking Raptor",
  "reduzir a lembrancas": "Reduce to Memory",
  "reflexos de littjara": "Reflections of Littjara",
  "retiro da falesia": "Clifftop Retreat",
  "retomar": "Take It Back",
  "retorno a natureza": "Return to Nature",
  "retorno do falabravo": "Return of the Wildspeaker",
  "rhonas, o indomito": "Rhonas the Indomitable",
  "rishkar, renegado de peema": "Rishkar, Peema Renegade",
  "roubado pelas fadinas": "Stolen by the Fae",
  "ruina enterrada": "Buried Ruin",
  "sabia da espiral": "Gyre Sage",
  "sacerdotisa dos deuses esquecidos": "Priest of Forgotten Gods",
  "santuario despedacado": "Shattered Sanctum",
  "santuario dos serafins": "Seraph Sanctuary",
  "saqueador de semblantes": "Likeness Looter",
  "semeadora de tentacao": "Sower of Temptation",
  "sephara, lamina dos ceus": "Sephara, Sky's Blade",
  "serafim da aurora": "Seraph of Dawn",
  "serafim de aco": "Steel Seraph",
  "serafim guardia dos alentos": "Breathkeeper Seraph",
  "serafim guardiao": "Guardian Seraph",
  "serpopardo espreitador": "Prowling Serpopard",
  "silfide hipnotica": "Hypnotic Sprite",
  "silfide magioclasta": "Spellstutter Sprite",
  "silfide zombeteira": "Mocking Sprite",
  "sinete arcano": "Arcane Signet",
  "sinete dimir": "Dimir Signet",
  "soberano de glen elendra": "Glen Elendra Liege",
  "supervisor inspirador": "Inspiring Overseer",
  "surrak, o convocador da cacada": "Surrak, the Hunt Caller",
  "talion, o lorde gentil": "Talion, the Kindly Lord",
  "talisma da dominacao": "Talisman of Dominance",
  "tegwyll, duque do esplendor": "Tegwyll, Duke of Splendor",
  "tempestade empirea": "Empyrial Storm",
  "templo do engano": "Temple of Deceit",
  "templo do falso deus": "Temple of the False God",
  "templo do silencio": "Temple of Silence",
  "templo do triunfo": "Temple of Triumph",
  "tentacao da vinganca": "Tempt with Vengeance",
  "territorio dos necrofagos": "Scavenger Grounds",
  "teste desconcertante": "Perplexing Test",
  "thalisse, medium reverente": "Thalisse, Reverent Medium",
  "tita de sol": "Sun Titan",
  "titereiras de sombras": "Shadow Puppeteers",
  "tocar o reino dos espiritos": "Touch the Spirit Realm",
  "torre do relicario": "Reliquary Tower",
  "trapaca feerica": "Faerie Trickery",
  "traquinas arrombador": "Picklock Prankster",
  "tremores de impacto": "Impact Tremors",
  "trol cacado": "Hunted Troll",
  "vale afundado": "Sunken Hollow",
  "vale apartado": "Secluded Glen",
  "vanguarda de sigarda": "Sigarda's Vanguard",
  "vastidao morfoterrena": "Terramorphic Expanse",
  "vegetacao explosiva": "Explosive Vegetation",
  "ventos favoraveis": "Favorable Winds",
  "veu de pele de serpente": "Snakeskin Veil",
  "vidente fada": "Faerie Seer",
  "vidente visceral": "Viscera Seer",
  "vigia de thraben": "Thraben Watcher",
  "vigiar": "Keep Watch",
  "visita divina": "Divine Visitation",
  "vortice monstruoso": "Monstrous Vortex",
  "yeva, arauto da natureza": "Yeva, Nature's Herald",
  "yorvo, senhor de pontegaren": "Yorvo, Lord of Garenbrig"
};

const NORMALIZED_ALIASES = new Map<string, string>(
  Object.entries(LOCAL_ALIASES).map(([input, canonical]) => [normalizeCardName(input), canonical])
);

export function applyLocalAlias(name: string): string | null {
  return NORMALIZED_ALIASES.get(normalizeCardName(name)) || null;
}
