import { normalizeCardName } from "./normalize-card-name.ts";

export const LOCAL_ALIASES: Record<string, string> = {
  "pantano": "Swamp",
  "pântano": "Swamp",
  "ritual sombrio": "Dark Ritual",
  "tutor diabolico": "Diabolic Tutor",
  "tutor diabólico": "Diabolic Tutor",
  "pedra da mente": "Mind Stone",
  "diamante de carvao": "Charcoal Diamond",
  "diamante de carvão": "Charcoal Diamond",
  "gavinhas da agonia": "Tendrils of Agony",
  "mercador cinzento de asfodelos": "Gray Merchant of Asphodel",
  "cidadela de nicol bolas": "Bolas's Citadel",
  "maquinacoes de gonti": "Gonti's Machinations",
  "maquinações de gonti": "Gonti's Machinations",
  "alimentar o enxame": "Feed the Swarm",
  "malignidade imortal": "Undying Malice",
  "armadura de sombras": "Armor of Shadows",
  "presenca medonha": "Dread Presence",
  "presença medonha": "Dread Presence",
  "lente prismatica": "Prismatic Lens",
  "lente prismática": "Prismatic Lens",
  "pluma do paraiso": "Paradise Plume",
  "pluma do paraíso": "Paradise Plume",
  "chifre de demonio": "Demon's Horn",
  "chifre de demônio": "Demon's Horn",
  "promessa de poder": "Promise of Power",
  "chainer mestre da demencia": "Chainer, Dementia Master",
  "chainer mestre da demência": "Chainer, Dementia Master",
  "pestilencia": "Pestilence",
  "pestilência": "Pestilence",
  "elixir da imortalidade": "Elixir of Immortality",
  "passagem do ladino": "Rogue's Passage",
  "parasita thrull": "Thrull Parasite",
  "sibilador da basilica": "Basilica Screecher",
  "sibilador da basílica": "Basilica Screecher",
  "impositor do sindicato": "Syndicate Enforcer",
  "pontifice do flagelo": "Pontiff of Blight",
  "pontífice do flagelo": "Pontiff of Blight",
  "cajado do magus da morte": "Staff of the Death Magus",
  "fonte radiante": "Radiant Fountain",
  "anel de prisma": "Prism Ring",
  "fonte das agonias": "Font of Agonies",
  "macular": "Defile",
  "rito de razaketh": "Razaketh's Rite",
  "torre de comando": "Command Tower",
  "manto de seda ruflante": "Whispersilk Cloak",
  "leia os ossos": "Read the Bones",
  "paisagem infinita": "Myriad Landscape",
  "dragao decadente": "Decadent Dragon",
  "dragão decadente": "Decadent Dragon",
  "gosto refinado": "Expensive Taste",
  "impeto brilhante": "Shiny Impetus",
  "ímpeto brilhante": "Shiny Impetus",
  "onda desmanteladora": "Dismantling Wave",
  "redemoinho de pensamentos": "Whirlwind of Thought",
  "mangara, o diplomata": "Mangara, the Diplomat",
  "epifania sublime": "Sublime Epiphany",
  "comando de prismari": "Prismari Command",
  "arquimago emerito": "Archmage Emeritus",
  "arquimago emérito": "Archmage Emeritus",
  "artista da fornalha tempestuosa": "Storm-Kiln Artist",
  "velomaco sapioforte": "Velomachus Lorehold",
  "iteracao expressiva": "Expressive Iteration",
  "iteração expressiva": "Expressive Iteration",
  "veyran, voz da dualidade": "Veyran, Voice of Duality",
  "considerar": "Consider",
  "lier, discipulo dos afogados": "Lier, Disciple of the Drowned",
  "lier, discípulo dos afogados": "Lier, Disciple of the Drowned",
  "subjugar a horda": "Vanquish the Horde",
  "dragao averneo manaforme": "Manaform Hellkite",
  "dragão averneo manaforme": "Manaform Hellkite",
  "sorte grande": "Big Score",
  "genio arrogante": "Haughty Djinn",
  "gênio arrogante": "Haughty Djinn",
  "iconoclasta da terceira via": "Third Path Iconoclast",
  "baral e kari zev": "Baral and Kari Zev",
  "planicie": "Plains",
  "ilha": "Island",
  "montanha": "Mountain",
  "floresta": "Forest",
  "mascara de avacyn": "Mask of Avacyn",
  "fera interior": "Beast Within",
  "batedor chifre-de-cobre": "Copperhorn Scout",
  "elfo do arvoredo": "Arbor Elf",
  "druida devotado": "Devoted Druid",
  "elfo porto-longinquo": "Farhaven Elf",
  "proeza do belo": "Prowess of the Fair",
  "passo elfico": "Elvish Promenade",
  "magistrado imaculado": "Immaculate Magistrate",
  "perfeita imperiosa": "Imperious Perfect",
  "dourador de folhas": "Leaf Gilder",
  "mestre de caca de lys alana": "Lys Alana Huntmaster",
  "retorno aterrorizante": "Dread Return",
  "garra krosana": "Krosan Grip",
  "elfos de fyndhorn": "Fyndhorn Elves",
  "elfos das sombras profundas": "Elves of Deep Shadow",
  "pastoras magi-anuladoras": "Nullmage Shepherd",
  "putrificar": "Putrefy",
  "chifres de vorrac para combate": "Vorrac Battlehorns",
  "elfo vigia dos pinheiros": "Timberwatch Elf",
  "drenar mente": "Mind Drain",
  "patrulheiros betulineos": "Birchlore Rangers",
  "voz das matas": "Voice of the Woods",
  "mortos de llanowar": "Llanowar Dead",
  "inconsciente coletivo": "Collective Unconscious",
  "sacerdote de titania": "Priest of Titania",
  "elfos da floresta": "Wood Elves",
  "patrulheiro de skyshroud": "Skyshroud Ranger",
  "vitalizar": "Vitalize",
  "arqueodruida elfo": "Elvish Archdruid",
  "elfos de llanowar": "Llanowar Elves",
  "homicidio": "Murder",
  "amuleto golgari": "Golgari Charm",
  "autoridade de alfa": "Alpha Authority",
  "mistico elfico": "Elvish Mystic",
  "elmo do espreitador": "Prowler's Helm",
  "templo da enfermidade": "Temple of Malady",
  "sabio da reivindicacao": "Reclamation Sage",
  "no rastro de garruk": "In Garruk's Wake",
  "clareira na selva": "Jungle Hollow",
  "revelacao xamanica": "Shamanic Revelation",
  "pacto condenavel": "Damnable Pact",
  "dwynen, daen de folha d'ouro": "Dwynen, Gilt-Leaf Daen",
  "xama do bando": "Shaman of the Pack",
  "druida do capote": "Druid of the Cowl",
  "bestiario do vivideiro": "Lifecrafter's Bestiary",
  "marwyn, a nutriz": "Marwyn, the Nurturer",
  "arqueiro da ponta envenenada": "Poison-Tip Archer",
  "encantador de feras": "Beast Whisperer",
  "druida do paraiso": "Paradise Druid",
  "baixas de guerra": "Casualties of War",
  "tribo de llanowar": "Llanowar Tribe",
  "recuperacao das gavinhas bolorentas": "Moldervine Reclamation",
  "mistica da mata": "Woodland Mystic",
  "escudo espelhado": "Mirror Shield",
  "ritos da vila": "Village Rites",
  "abominacao de llanowar": "Abomination of Llanowar",
  "abismo da floresta": "Woodland Chasm",
  "umbrosabia de skemfar": "Skemfar Shadowsage",
  "harald, rei de skemfar": "Harald, King of Skemfar",
  "vingadora de skemfar": "Skemfar Avenger",
  "coroa de skemfar": "Crown of Skemfar",
  "peconha da presa ancestral": "Elderfang Venom",
  "pacto da serpente": "Pact of the Serpent",
  "ponte de musgosombrio": "Darkmoss Bridge",
  "paisagem perigosa": "Perilous Landscape"
};

const NORMALIZED_ALIASES = new Map<string, string>(
  Object.entries(LOCAL_ALIASES).map(([input, canonical]) => [normalizeCardName(input), canonical])
);

export function applyLocalAlias(name: string): string | null {
  return NORMALIZED_ALIASES.get(normalizeCardName(name)) || null;
}
